not-installed-message: "%plugin% is not installed, you can download it at %link%!"
# Format is plugin name : true | false
# if true, the server will be stopped
required-plugins:
  multiverse:
    stop-server: false
    download-link: "www.example.com"